# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-news-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-news-app
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod "SwiftSpinner"
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'Charts'
end
